# Generated by Django 4.1.7 on 2023-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AddField(
            model_name='facture',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='typedf',
            field=models.CharField(choices=[('R', 'Reçu'), ('P', 'PROFORMA FACTURE'), ('F', 'Facture')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
