# Generated by Django 4.1.7 on 2023-04-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0002_alter_facture_options_facture_comments_facture_payer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantite', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='article')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.facture')),
            ],
        ),
    ]
