# Generated by Django 4.1.7 on 2023-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.CharField(max_length=4),
        ),
    ]
